import { NotificationDto, SkillDetail, SkillSummary, UserSummary } from '../common/p1-contracts';

const now = '2026-04-11T02:30:00Z';

export const p1User: UserSummary = {
  userID: 'u_001',
  displayName: '张三',
  role: 'normal_user',
  departmentID: 'dept_frontend',
  departmentName: '前端组',
  locale: 'zh-CN',
};

export const p1Skills: SkillDetail[] = [
  {
    skillID: 'codex-review-helper',
    displayName: 'Codex Review Helper',
    description: '为 Codex 项目提供代码审查提示和提交前检查清单。',
    version: '1.2.0',
    status: 'published',
    visibilityLevel: 'public_installable',
    detailAccess: 'full',
    canInstall: true,
    installState: 'not_installed',
    authorName: '李四',
    authorDepartment: '前端组',
    currentVersionUpdatedAt: now,
    compatibleTools: ['codex', 'custom_directory'],
    compatibleSystems: ['macos', 'windows', 'linux'],
    icon: '/assets/skills/codex-review-helper/icon.png',
    tags: ['codex', 'review', 'quality'],
    category: 'engineering',
    starCount: 12,
    downloadCount: 33,
    riskLevel: 'low',
    readme: '安装后在 Codex skills 目录中启用代码审查提示。',
    usage: '下载并通过 Desktop 选择 Codex 工具启用，默认 symlink，失败时 copy 降级。',
    screenshots: ['/assets/skills/codex-review-helper/screenshot-1.png'],
    reviewSummary: 'P1 审核通过：仅包含提示词和 README。',
    riskDescription: '低风险：不含可执行二进制。',
    versions: [{ version: '1.2.0', publishedAt: now }],
    enabledTargets: [],
    latestVersion: '1.2.0',
    hasUpdate: false,
    canUpdate: false,
  },
  {
    skillID: 'design-guideline-lite',
    displayName: 'Design Guideline Lite',
    description: '企业 UI 规范摘要，详情仅对授权部门开放。',
    version: '0.9.0',
    status: 'published',
    visibilityLevel: 'summary_visible',
    detailAccess: 'summary',
    canInstall: false,
    cannotInstallReason: 'permission_denied',
    installState: 'blocked',
    authorName: '王五',
    authorDepartment: '设计平台组',
    currentVersionUpdatedAt: now,
    compatibleTools: ['codex', 'claude'],
    compatibleSystems: ['macos', 'windows'],
    tags: ['design', 'restricted'],
    category: 'design',
    starCount: 4,
    downloadCount: 8,
    riskLevel: 'unknown',
    enabledTargets: [],
    latestVersion: '0.9.0',
    hasUpdate: false,
    canUpdate: false,
  },
  {
    skillID: 'legacy-dept-runbook',
    displayName: 'Legacy Department Runbook',
    description: '已下架的部门运行手册，验证不可安装场景。',
    version: '2.0.1',
    status: 'delisted',
    visibilityLevel: 'detail_visible',
    detailAccess: 'full',
    canInstall: false,
    cannotInstallReason: 'skill_delisted',
    installState: 'blocked',
    authorName: '赵六',
    authorDepartment: '运维组',
    currentVersionUpdatedAt: now,
    compatibleTools: ['custom_directory'],
    compatibleSystems: ['linux'],
    tags: ['ops', 'delisted'],
    category: 'operations',
    starCount: 1,
    downloadCount: 2,
    riskLevel: 'medium',
    readme: '该 Skill 已下架，仅用于 P1 验收。',
    enabledTargets: [],
    latestVersion: '2.0.1',
    hasUpdate: false,
    canUpdate: false,
  },
];

export const p1Notifications: NotificationDto[] = [
  {
    notificationID: 'n_001',
    type: 'connection_restored',
    title: '服务连接已恢复',
    summary: 'Desktop 已重新连接到企业内网 API。',
    objectType: 'connection',
    createdAt: now,
    read: false,
    action: '/notifications',
  },
  {
    notificationID: 'n_002',
    type: 'skill_update_available',
    title: 'Skill 有可用更新',
    summary: 'Codex Review Helper 有新版本可安装。',
    objectType: 'skill',
    objectID: 'codex-review-helper',
    createdAt: now,
    read: true,
    action: '/skills/codex-review-helper',
  },
];

export function summarizeSkill(skill: SkillDetail): SkillSummary {
  return {
    skillID: skill.skillID,
    displayName: skill.displayName,
    description: skill.description,
    version: skill.version,
    status: skill.status,
    visibilityLevel: skill.visibilityLevel,
    detailAccess: skill.detailAccess,
    canInstall: skill.canInstall,
    cannotInstallReason: skill.cannotInstallReason,
    installState: skill.installState,
    authorName: skill.authorName,
    authorDepartment: skill.authorDepartment,
    currentVersionUpdatedAt: skill.currentVersionUpdatedAt,
    compatibleTools: skill.compatibleTools,
    compatibleSystems: skill.compatibleSystems,
    icon: skill.icon,
    tags: skill.tags,
    category: skill.category,
    starCount: skill.starCount,
    downloadCount: skill.downloadCount,
    riskLevel: skill.riskLevel,
  };
}
